version:0.1
phases:
  install:
    commands:
      - echo Installing NGINX 
      - sudo apt-get update
      - supd apt-get install nginx -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/

    post_build:
      commands:
        - echo configuring NGINX

  artifact:
    files:
      - /var/www/html/index.html